language: python
python:
  - "2.7"
env:
  - NUMPY_VERSION=1.7.0
#  - NUMPY_VERSION=1.7.2
#  - NUMPY_VERSION=1.9.2
#  - NUMPY_VERSION=1.9.3
#  - NUMPY_VERSION=1.10.4
  - NUMPY_VERSION=1.11.1

install: "pip install -U pip setuptools"

script:
  - pip uninstall --yes numpy
  - pip install numpy==$NUMPY_VERSION
